# Generated by Django 4.1.6 on 2023-02-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenAllowance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("token_name", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
