# Generated by Django 4.1.6 on 2023-02-16 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_tokenallowance_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenallowance",
            options={"ordering": ["-amount"]},
        ),
    ]
